### ISSUE TITLE
Error on first build

### ISSUE THREAD

**Issue by MayhemBliz** [MajorDigital/ox#1]
Error in plugin 'sass'
Message:
    src\scss\utils\_normalize.scss
Error: Invalid CSS after "... display in IE.": expected 1 selector or at-rule, was "article,"
        on line 18 of src/scss/utils/_normalize.scss
>> }

events.js:141
      throw er; // Unhandled 'error' event
      ^
 Error: C:\Users\sean\Dropbox\Projects\sial\src\scss\utils\_normalize.scss:38:1: Unexpected }
    display: block;
}

**Comment by djhsecondnature** [comment]
Fixed in v 2.0.5. Was a trio of errors in the new customised normalize.
