### ISSUE TITLE
.no-fouc not being removed at the start of the webpage loading

### ISSUE THREAD

**Issue by Kryptikoz** [MajorDigital/ox#2]
The no-fouc class isn't being removed when the document has finished loading, from the looks of it requires the following code in the core.js : 
$('.no-fouc').removeClass('no-fouc');

under the document.ready statement

Thanks,
Chris

**Comment by MayhemBliz** [comment]
Also having this issue. I added it as a function:

/*---------------------------------
	FOUC
-----------------------------------*/
function fouc() {
    $('.no-fouc').removeClass('no-fouc');
}

then added it to ready

**Comment by djhsecondnature** [comment]
Added in v 0.2.10 which I will push live later.
