### ISSUE TITLE
Change number of elements in deck

### ISSUE THREAD

**Issue by SeanGPalmer** [MajorDigital/ox#9]
`@function grid-cols($fr:$grid-cards) {
    $col: "1fr";
    $content: "";
    @for $i from 1 through $fr {
        $content: $content + " " + $col;
    }
    @return #{$content};
}

@supports(display: grid) {
    .deck {
        display: grid;
        grid-template-columns: grid-cols();
        grid-gap: $grid-gutter;
    }
    .deck--five {
        display: grid;
        grid-template-columns: grid-cols(5);
        grid-gap: $grid-gutter;
    }
}`

**Comment by davshoward** [comment]
Will be in next commit.
